api/urls.py
from django.urls import path
from api import views
from api.views import UserCreationView
from rest_framework.routers import DefaultRouter

router=DefaultRouter()
router.register("cakes",views.CakeView,basename="cakes")

urlpatterns=[
    path("register",UserCreationView.as_view())
    



]+router.urls                                                                                           

cakebox/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("cakebox/api/",include("api.urls")),
    path('',include('cakeoperations.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cakeoperations/urls.py
from django.urls import path
from cakeoperations.views import SignUpView,SignInView,IndexView,CakeCreateView,CategoryCreateView,\
CakeListView,CakeUpdateView,remove_cakeview,CakeDetailView,CakeVarientCreateView,CakeVarientUpdateView,remove_varient,\
OfferCreateView,offer_delete_view,sign_out_view



urlpatterns=[
    path('signup/',SignUpView.as_view(),name='signin'),
    path('',SignInView.as_view(),name='login'),
    path('index/',IndexView.as_view(),name='index'),
    path('cake/add',CakeCreateView.as_view(),name='cake-add'),
    path('category/add',CategoryCreateView.as_view(),name='category-add'),
    path('cake/list',CakeListView.as_view(),name='cake-list'),
    path('cake/<int:pk>/change',CakeUpdateView.as_view(),name='cake-change'),
    path('cake/<int:pk>/remove',remove_cakeview,name="cake-remove"),
    path('cake/<int:pk>/',CakeDetailView.as_view(),name='cake-detail'),
    path('cake/<int:pk>/varient/add',CakeVarientCreateView.as_view(),name='varient-add'),
    path('cake/<int:pk>/varient/change',CakeVarientUpdateView.as_view(),name='varient-change'),
    path('cake/<int:pk>/varient/remove',remove_varient,name='varient-remove'),
    path('offers/<int:pk>/add',OfferCreateView.as_view(),name='offer-add'),
    path('offers/<int:pk>/delete',offer_delete_view,name='offer-delete'),
    path('logout/',sign_out_view,name='signout')
]

cakeoperations/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.


class User(AbstractUser): 
    address=models.CharField(max_length=200)
    phone=models.CharField(max_length=100,unique=True)
    
class Category(models.Model):

    caketype=models.CharField(max_length=200,unique=True)
    is_active=models.BooleanField(default=True)
    
    
    def __str__(self):
        return self.caketype
    
class Cakes(models.Model):
    
    name=models.CharField(max_length=200)
    description=models.CharField(max_length=200)
    image=models.ImageField(upload_to="images")
    category=models.ForeignKey(Category,on_delete=models.CASCADE)


    def __str__(self):
        return self.name
    
class CakeVarients(models.Model):
    price=models.PositiveIntegerField()
    options=(
        ("250g","250g"),
        ("500g","500g"),
        ("1kg","1kg"),
        ("1.5kg","1.5kg"),
        ("2kg","2kg")
    )
    weight=models.CharField(max_length=100,choices=options,default="1kg")
    # cake_message=models.CharField(max_length=200)
    cake=models.ForeignKey(Cakes,on_delete=models.CASCADE)
   
class Offer(models.Model):
    cakevarient=models.ForeignKey(CakeVarients,on_delete=models.CASCADE)
    price=models.PositiveIntegerField()
    start_date=models.DateTimeField()
    due_date=models.DateTimeField()
    
class Cart(models.Model):
    cakevarient=models.ForeignKey(CakeVarients,on_delete=models.DO_NOTHING)
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    options=(
        ("in-cart","in-cart"),
        ("order-placed","order-placed"),
        ("cancelled","cancelled")
    )
    status=models.CharField(max_length=100,choices=options,default="in-cart")
    date=models.DateTimeField(auto_now_add=True)
    
class Orders(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    cakevarient=models.ForeignKey(CakeVarients,on_delete=models.CASCADE)
    options=(
        ("order-placed","order-placed"),
        ("cancelled","cancelled"),
        ("dispatched","dispatched"),
        ("in-transit","in-transit"),
        ("delivered","delivered")
    )
    status=models.CharField(max_length=100,choices=options,default="order-placed")
    ordered_date=models.DateTimeField(auto_now_add=True)
    expected_date=models.DateField(null=True)
    address=models.CharField(max_length=200)
    
    
from django.core.validators import MinValueValidator,MaxValueValidator
class Reviews(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    cakevarient=models.ForeignKey(CakeVarients,on_delete=models.CASCADE)
    rating=models.PositiveIntegerField(validators=[MinValueValidator(1),MaxValueValidator(5)])
    comment=models.CharField(max_length=200)

cakeoperations/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from cakeoperations.models import User,Category,Cakes,Offer,CakeVarients


class RegistrationForm(UserCreationForm):
    class Meta:
        model=User
        fields=['username','email','password1','password2','phone','address']

class LoginForm(forms.Form):
    username=forms.CharField(max_length=100)
    password=forms.CharField(widget=forms.PasswordInput)

class CategoryCreateForm(forms.ModelForm):

    class Meta:
        model=Category
        fields=['caketype']

class CakeCreateForm(forms.ModelForm):
    class Meta:
        model=Cakes
        fields=('__all__')

class CakeVarientForm(forms.ModelForm):
    class Meta:
        model=CakeVarients
        fields="__all__"

class OfferCreateForm(forms.ModelForm):
    class Meta:
        model=Offer
        exclude=('cakevarient',)
        widgets={
        "start_date":forms.DateInput(attrs={"type":"date"}),
        "due_date":forms.DateInput(attrs={"type":"date"}),

        }

cakeoperations/views.py
from django.forms.models import BaseModelForm
from django.http import HttpResponse
from django.shortcuts import render,redirect
from django.views.generic import CreateView,FormView,TemplateView,ListView,UpdateView,DeleteView,DetailView
from django.contrib import messages
from django.urls import reverse_lazy
from django.contrib.auth import authenticate,login,logout


from cakeoperations.models import User,Cakes,Category,CakeVarients,Offer
from cakeoperations.forms import RegistrationForm,LoginForm,CakeCreateForm,CategoryCreateForm,CakeVarientForm,\
OfferCreateForm




# Create your views here.
class SignUpView(CreateView):
    template_name='cake/register.html'
    form_class=RegistrationForm
    model=User
    success_url=reverse_lazy('login.html')

    def form_valid(self, form):
        messages.success(self.request,'registration successfully')
        return super().form_valid(form)
    def form_invalid(self,form):
        messages.error(self.request,'registration failed')
        return super().form_invalid(form)
    
class SignInView(FormView):
    template_name=('cake/login.html')
    form_class=LoginForm

    def post(self,request,*args,**kwargs):
        form=LoginForm(request.POST)
        if form.is_valid():
            uname=form.cleaned_data.get("username")
            pwd=form.cleaned_data.get("password")
            usr=authenticate(request,username=uname,password=pwd)
            if usr:
                login(request,usr)
                messages.success(request,"login successfully")
                return redirect("index")
            else:
                messages.error(request,"invalid creadential")
                return render(request,self.template_name,{"form":form})
            
class IndexView(TemplateView):
    template_name='cake/index.html'

class CakeCreateView(CreateView):
    template_name='cake/cake_add.html'
    model=Cakes
    form_class=CakeCreateForm
    success_url=reverse_lazy('cake-add')

    def form_valid(self, form):
        messages.success(self.request,'cake added succesfully')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.errors(self.request,'failed')
        return super().form_invalid(form)
    
class CategoryCreateView(CreateView):
    template_name="cake/category_add.html"
    form_class=CategoryCreateForm
    model=Category
    context_object_name="categories"
    success_url=reverse_lazy("category-add")
    def form_valid(self,form):
        messages.success(self.request,"category added successfully")
        return super().form_valid(form)
    
    def form_invalid(self, form):
        messages.error(self.request,"category adding failed")
        return super().form_invalid(form)


class CakeListView(ListView):
    template_name="cake/cake_list.html"
    model=Cakes
    context_object_name="cakes"

class CakeUpdateView(UpdateView):
    template_name="cake/update.html"
    model=Cakes
    form_class=CakeCreateForm
    success_url=reverse_lazy("cake-list")

    def form_valid(self, form):
        messages.success(form,"updated successfully")
        return super().form_valid(form)
    def form_invalid(self,form):
        messages.error(form,"updation failed!!!")
        return super().form_invalid(form)
    
def remove_cakeview(request,*args,**kwargs):
    id=kwargs.get("pk")
    Cakes.objects.filter(id=id).delete()
    return redirect('cake-list')

class CakeDetailView(DetailView):
    template_name="cake/detail.html"
    model=Cakes
    context_object_name="cake"

class CakeVarientCreateView(CreateView):
    template_name="cake/cakevarient_add.html"
    form_class=CakeVarientForm
    model=CakeVarients
    success_url=reverse_lazy("cake-list")   

    def form_valid(self, form):
        id=self.kwargs.get("pk")
        obj=Cakes.objects.get(id=id)
        form.instance.cake=obj
        messages.success(self.request,"varient has been added")
        return super().form_valid(form)
    
class CakeVarientUpdateView(UpdateView):
    template_name='cake/cakevarient_update.html'
    form_class=CakeVarientForm
    model=CakeVarients
    success_url=reverse_lazy("cake-list")

    def form_valid(self,form):
        messages.success(self.request,"successfully updated")
        return super().form_valid(form)
    
    def form_invalid(self,form):
        messages.error(self.request,"updation failed")
        return super().form_invalid(form)
    

def remove_varient(request,*args,**kwargs):
    id=kwargs.get("pk")
    Cakes.objects.get(id=id).delete()
    return redirect('cake-list')

class OfferCreateView(CreateView):
    template_name="cake/offer.html"
    model=Offer
    form_class=OfferCreateForm
    success_url=reverse_lazy('cake-list')

    def form_valid(self,form):
        id=self.kwargs.get("pk")
        obj=CakeVarients.objects.get(id=id)  #error
        form.instance.cakevarient=obj
        messages.success(self.request,"offer has been added successfully")
        return super().form_valid(form)
    
def offer_delete_view(request,*args,**kwargs):
    id=kwargs.get('pk')
    offer_object=Offer.objects.get(id=id)
    cake_id=offer_object.cakevarient.cake.id  #error
    offer_object.delete()
    return redirect('cake-detail',pk=cake_id)

def sign_out_view(request,*args,**kwargs):
    logout(request)
    return redirect('signin')

cakeoperations/templates/cake/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Simple Sidebar - Start Bootstrap Template</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{%static 'css/styles.css'%}" rel="stylesheet" />
    </head>
    <body>
        <div class="d-flex" id="wrapper">
            <!-- Sidebar-->
            <div class="border-end bg-white" id="sidebar-wrapper">
                <div class="sidebar-heading border-bottom bg-light">Start Bootstrap</div>
                <div class="list-group list-group-flush">
                    <a class="list-group-item list-group-item-action list-group-item-light p-3" href="#!">Dashboard</a>
                    <a class="list-group-item list-group-item-action list-group-item-light p-3" href="{%url 'category-add'%}">Category add</a>
                    <a class="list-group-item list-group-item-action list-group-item-light p-3" href="{%url 'cake-add'%}">Cake Add</a>
                    <a class="list-group-item list-group-item-action list-group-item-light p-3" href="{%url 'cake-list'%}">Explore</a>
                    <a class="list-group-item list-group-item-action list-group-item-light p-3" href="#!">Profile</a>
                    <a class="list-group-item list-group-item-action list-group-item-light p-3" href="#!">Status</a>
                </div>
            </div>
            <!-- Page content wrapper-->
            <div id="page-content-wrapper">
                <!-- Top navigation-->
                <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
                    <div class="container-fluid">
                        <button class="btn btn-primary" id="sidebarToggle">Toggle Menu</button>
                        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                        <div class="collapse navbar-collapse" id="navbarSupportedContent">
                            <ul class="navbar-nav ms-auto mt-2 mt-lg-0">
                                <li class="nav-item active"><a class="nav-link" href="#!">Home</a></li>
                                <li class="nav-item"><a class="nav-link" href="">Logout</a></li>
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown</a>
                                    <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                        <a class="dropdown-item" href="#!">Action</a>
                                        <a class="dropdown-item" href="#!">Another action</a>
                                        <div class="dropdown-divider"></div>
                                        <a class="dropdown-item" href="#!">Something else here</a>
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </div>
                </nav>
                <!-- Page content-->
                <div class="container-fluid">
                   {%block body_block%}
                   {%endblock%}
                </div>
            </div>
        </div>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{%static 'js/scripts.js'%}"></script>
    </body>
</html>

cakeoperations/templates/cake/cake_add.html
{%extends 'cake/base.html'%}
{%block body_block%}
<div class="container d-flex align-items-center justify-content-center">
  <form action="" method="post" enctype="multipart/form-data" class="border border-2 shadow p-5">

      {%csrf_token%}
      {{form.as_p}}
      <input type="submit" value="add">
  </form>

{%endblock%}

cakeoperations/templates/cake/cake_list.html
{%extends 'cake/base.html'%}
{%block body_block%}
<div class="container">
    {%csrf_token%}

    <table class="table table-striped">

        <tr>
            <td>Name</td>
            <td>Category</td>
            <td>image</td>
        </tr>

        {%for ct in cakes%}
        <tr>
            <td>{{ct.name}}</td>
            <td>{{ct.category}}</td>
            <td>
                <img src="{{ct.image.url}}" alt="" width="100px" height="200px" style="object-fit: contain;">
            </td>

            <td>
                <a href="{%url 'cake-remove' ct.id%}">delete</a>
                <a href="{%url 'cake-detail' ct.id%}">view</a>
                <a href="{%url 'varient-add' ct.id%}">Add varient</a>
            </td>
        </tr>
        {%endfor%}

    </table>




</div>
{%endblock%}

cakeoperations/templates/cake/cakevarient_add.html
{%extends 'cake/base.html'%}
{%block body_block %}
{%if messages%}
    {%for m in messages%}

      <div>
        {{m}}
      </div>
    {%endfor%}

{%endif%}

    
<div class="container d-flex align-items-center justify-content-center">
    <form action="" method="post" enctype="multipart/form-data" class="border border-2 shadow p-5">

        {%csrf_token%}
        {{form.as_p}}
        <input type="submit" value="add">
    </form>


</div>

{%endblock%}

cakeoperations/templates/cake/cakevarient_update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body style="height:100vh;">

{%if messages%}
    {%for m in messages%}

      <div>
        {{m}}
      </div>
    {%endfor%}

{%endif%}

    
<div class="container d-flex align-items-center justify-content-center">
    <form action="" method="post" enctype="multipart/form-data" class="border border-2 shadow p-5">

        {%csrf_token%}
        {{form.as_p}}
        <input type="submit" value="add">
    </form>


</div>

</body>
</html>

cakeoperations/templates/cake/category_add.html
{%extends 'cake/base.html'%}
{%block body_block%}
<div class="container d-flex flex-column align-items-center mt-5">
    <div class="border border-4 p-5">
     <h1 class="text-center mb-3">Categories</h1>
     <div class="w-100">
      <form action="" method="post">
  
          {%csrf_token%}
          {{form.as_p}}
          <input type="submit" value="add">
      </form>
  
     </div>
  
     <div class="mt-5 w-100">
      <table class="table table-striped">
          <tr>
              <td>Name</td>
              <td>Action</td>
          </tr>
          {%for cat in categories%}
             <tr>
              <td>{{cat.name}}</td>
              <td>
                  <a href="{%url 'remove-category' cat.id%}">delete</a>
              </td>
      
             </tr>
          {%endfor%}
      
      </table>
     </div>
  
    </div>
 
 
    
 
 
 </div>
{%endblock%}

cakeoperations/templates/cake/detail.html
{%extends 'cake/base.html'%}
{%block body_block%}
<div class="container">

  <div class="row">

    <div class="col-4">
      <div class="card" style="width:60%">
        <img src="{{cake.image.url}}" class="card-img-top" alt="..." height="200px">
        <div class="card-body">
          <h5 class="card-title">{{cake.name}}</h5>
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item">{{cloth.material}}</li>
          <li class="list-group-item">{{cloth.category}}</li>
        </ul>
        <div class="card-body">
          <a href="#" class="card-link">Card link</a>
          <a href="#" class="card-link">Another link</a>
        </div>
      </div>
    </div>
    <div class="col-8 border boredr-dark">
      <table class="table table-striped">
        <tr>

          <td>Price</td>
          <td>weight</td>
          <td>offers</td>
          <td>Action</td>
        </tr>
        {%for v in cake.cakevarients_set.all%}

        <tr>
          <td>{{v.price}}</td>
          <td>{{v.weight}}</td>
          <td>{{v.color}}</td>
          <td>
            <div class="accordion" id="accordionExample">
              <div class="accordion-item">
                <h2 class="accordion-header">
                  <button class="accordion-button" type="button" data-bs-toggle="collapse"
                    data-bs-target="#collapseOne{{forloop.counter}}" aria-expanded="true" aria-controls="collapseOne">
                    offers
                  </button>
                </h2>
                <div id="collapseOne{{forloop.counter}}" class="accordion-collapse collapse show"
                  data-bs-parent="#accordionExample">
                  <div class="accordion-body">


                    {%for o in v.offers_set.all%}

                    <div class="border border-top-0 border-start-0 border-end-0 border-bottom-1">
                      price:{{o.price}} start_date:{{o.start_date|date:"SHORT_DATE_FORMAT"}} |due_date :{{o.due_date|date:"SHORT_DATE_FORMAT"}}


                    </div>
                    {%endfor%}

                  </div>
                </div>
              </div>
            </div>
    </div>
    </td>

    <td>
      <a href="{%url 'varient-change' v.id %}" class="btn btn-outline-info">Edit</a>
      <a href="{%url 'varient-remove' v.id%}" class="btn btn-outline-danger">remove</a>

      <a href="{%url 'offer-add' v.id%}" class="btn btn-outline-success">add offer</a>
    </td>
    </tr>
    {%endfor%}

    </table>
  </div>





</div>

<div class="row">
  {%for v in cloth.clothvarients_set.all%}
  {%for o in v.offers_set.all%}
  <div class="border p-3">

    <div>
      size {{o.clothvarient.size}} | color {{o.clothvarient.color}}
    </div>

    <div><span>offer price$ {{o.price}}</span></div>
    <div>start_date : {{o.start_date}}</div>
    <div>due_date :{{o.due_date}}</div>
    <a href="{%url 'delete-offer' o.id%}">delete</a>
  </div>
  {%endfor%}

  {%endfor%}

</div>



</div>
{%endblock%}

cakeoperations/templates/cake/index.html
{%extends 'cake/base.html'%}
{%block body_block%}
welcome

{%endblock%}

cakeoperations/templates/cake/login.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>
    <style>
        body {
            height: 100vh;
            background-color: #4158D0;
            background-image: linear-gradient(43deg, #4158D0 0%, #C850C0 46%, #FFCC70 100%);

        }

        .section {
            width: 40%;
            height: 80%;

        }



        .btn-grad {
            background-image: linear-gradient(to right, #4776E6 0%, #8E54E9 51%, #4776E6 100%);
            margin: 10px;
            padding: 10px 45px;
            text-align: center;
            text-transform: uppercase;
            transition: 0.5s;
            background-size: 200% auto;
            color: white;
            box-shadow: 0 0 20px #eee;
            border-radius: 10px;
            display: block;
        }

        .btn-grad:hover {
            background-position: right center;
            /* change the direction of the change here */
            color: #fff;
            text-decoration: none;
        }
    </style>
</head>

<body>

    {%if messages%}
    <div class="container d-flex justify-content-center">
        <div class="w-50" style="height: 100px;">

            <div>
                {%for m in messages%}

                {%if m.level == DEFAULT_MESSAGE_LEVELS.ERROR %}

                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                    <strong>Holy guacamole!</strong> {{m}}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>

                {%endif%}


                {%endfor%}

            </div>


        </div>

    </div>

    {%endif%}

    <div class="container h-100 d-flex justify-content-center align-items-center">



        <div class="section rounded-3 bg-white p-5 shadow">
            <div class="text-center mb-5">
                <h1 class="fw-bolder">Login</h1>
            </div>
            <form action="" method="post">
                {%csrf_token%}
                <div class="mb-4">
                    <label for="" class="form-label">username</label>
                    <input type="text" placeholder="Type your username"
                        class="form-control border border-start-0 border-top-0 border-end-0" name="username">
                </div>
                <div class="mb-4">
                    <label for="" class="form-label">password</label>
                    <input type="text" placeholder="Type your password"
                        class="form-control border border-start-0 border-top-0 border-end-0" name="password">
                </div>
                <div>
                    <button class="form-control btn-grad rounded-pill" type="submit">Login</button>
                </div>

                <div class="social-auth d-flex flex-column align-items-center">

                    <div>
                        <label for="">or SignUpusging</label>

                    </div>

                    <div>
                        <a href="">fb</a>
                        <a href="">twitter</a>
                        <a href="">google</a>
                    </div>


                </div>


            </form>


        </div>

    </div>


</body>

</html>

cakeoperations/templates/cake/offer.html
{%extends 'cake/base.html'%}
{%block body_block%}
{%if messages%}
    {%for m in messages%}

      <div>
        {{m}}
      </div>
    {%endfor%}

{%endif%}

    
<div class="container d-flex align-items-center justify-content-center">
    <form action="" method="post" enctype="multipart/form-data" class="border border-2 shadow p-5">

        {%csrf_token%}
        {{form.as_p}}
        <input type="submit" value="add">
    </form>


</div>

{%endblock%}

cakeoperations/templates/cake/update.html
{%extends 'cake/base.html'%}
{%block body_block%}
<div class="container d-flex align-items-center justify-content-center">
  <form action="" method="post" enctype="multipart/form-data" class="border border-2 shadow p-5">

      {%csrf_token%}
      {{form.as_p}}
      <input type="submit" value="add">
  </form>

{%endblock%}